#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
// Generates src/generated/types.ts FROM the JSON Schema files in
// src/schemas/*.schema.json. This is the only place TypeScript types for
// chatbot-contracts are allowed to originate — JSON Schema is the single
// source of truth (024 task-breakdown T-10010). `test/type-parity.spec.ts`
// re-runs this generator into a temp file and diffs it against the checked
// in output, so any hand-edit of generated/types.ts is caught as a test
// failure instead of silently drifting from the schemas.
//
// All target schemas are compiled in a SINGLE `compile()` call via a
// synthetic `$defs` wrapper. Doing one call per file would make
// json-schema-to-typescript re-dereference and re-emit every shared
// sub-schema (AttachmentManifest, ContextManifest, StructuredError,
// ContentParts, ...) once per file that references it, producing duplicate
// `export interface` declarations that fail to compile.
import { compile } from 'json-schema-to-typescript';

const here = path.dirname(fileURLToPath(import.meta.url));
const schemasDir = path.join(here, '..', 'src', 'schemas');
const outDir = path.join(here, '..', 'src', 'generated');
const outFile = path.join(outDir, 'types.ts');

const SCHEMA_ID_PREFIX = 'https://chatbot-contracts.appspine.internal/v1/';

/** Resolves our internal https://chatbot-contracts.appspine.internal/... $ids
 * to local files instead of attempting a real network fetch. */
const localResolver = {
  order: 1,
  canRead: (file) => file.url.startsWith(SCHEMA_ID_PREFIX),
  read: (file) => {
    const fileName = file.url.slice(SCHEMA_ID_PREFIX.length);
    return readFileSync(path.join(schemasDir, fileName), 'utf8');
  },
};

const targets = [
  ['ingress-request.schema.json', 'IngressRequest'],
  ['ingress-acceptance.schema.json', 'IngressAcceptance'],
  ['claim-request.schema.json', 'ClaimRequest'],
  ['claim-response.schema.json', 'ClaimResponse'],
  ['completion.schema.json', 'CompletionCallback'],
  ['context-manifest.schema.json', 'ContextManifest'],
  ['attachment-manifest.schema.json', 'AttachmentManifest'],
  ['content-parts.schema.json', 'ContentParts'],
  ['typed-action.schema.json', 'TypedActionEvent'],
  ['structured-error.schema.json', 'StructuredError'],
  ['callback-challenge.schema.json', 'CallbackChallenge'],
];

async function main() {
  const wrapper = {
    $id: `${SCHEMA_ID_PREFIX}_all.schema.json`,
    $defs: {},
  };
  for (const [file, typeName] of targets) {
    wrapper.$defs[typeName] = { $ref: `${SCHEMA_ID_PREFIX}${file}` };
  }

  const ts = await compile(wrapper, 'ChatbotContractsRoot', {
    cwd: schemasDir,
    bannerComment: '',
    unreachableDefinitions: true,
    style: { semi: true, singleQuote: true },
    $refOptions: {
      resolve: {
        http: false,
        local: localResolver,
      },
    },
  });

  const header = [
    '// AUTO-GENERATED by scripts/generate-types.mjs FROM src/schemas/*.schema.json.',
    '// Do not hand-edit. Regenerate with `pnpm --filter @appspine/chatbot-contracts generate`.',
    '/* eslint-disable */',
    '',
  ].join('\n');

  // Drop the synthetic wrapper root interface generated for the `$defs`-only
  // container this script builds above; only the named $defs (IngressRequest,
  // ContextManifest, ...) are the real public surface of this package. The
  // wrapper's generated name is derived from its $id, not a fixed string.
  const withoutRoot = ts
    .replace(/export interface Https\w+ \{\n {2}\[k: string\]: unknown;\n\}\n*/, '')
    .replace(
      / *\*\n \* This interface was referenced by `Https\w+`'s JSON-Schema\n \* via the `definition` "\w+"\.\n/g,
      '',
    )
    .replace(/\/\*\*\n \*\/\n/g, '');

  mkdirSync(outDir, { recursive: true });
  writeFileSync(outFile, header + withoutRoot);
  console.log(`generated ${path.relative(process.cwd(), outFile)}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
