/**
 * `.appspine/generated/backend/composition.ts` (PL2-05).
 *
 * The one thing this file exists to guarantee: **static imports**. 051 plan §6.4 and §9 both
 * forbid resolving a package name at runtime, and the reason is not stylistic — a dynamic import
 * is invisible to the bundler, to TypeScript, and to a security review. Every plugin the App runs
 * has to appear as a real `import` statement that a reader, `tsc` and a dependency scanner all see.
 *
 * PL1-03 froze `GeneratedComposition` before this generator existed, so the host has had a working
 * consumer of this shape the whole time. That is why this file emits TypeScript rather than JSON:
 * the App compiles it, and a wrong export name fails the build loudly instead of at boot.
 */

import type { PluginDiagnostic } from '@appspine/plugin-api';
import { diagnostic } from '@appspine/plugin-api';
import type { GeneratedArtifact, GenerationInput } from './generate';
import { GENERATED_DIR, sourceDigest } from './generate';

export const COMPOSITION_ARTIFACT = `${GENERATED_DIR}/backend/composition.ts`;

/**
 * `health-check` -> `healthCheckPlugin`.
 *
 * A convention, and therefore only as good as its enforcement: `051-pl1-architecture-check.mjs`
 * asserts that every package with a manifest exports exactly this name from its `./plugin`
 * subpath. Without that rule this would be a guess that fails at the consumer's build, far from
 * the package that broke it.
 */
export function descriptorExportName(pluginId: string): string {
  const camel = pluginId.replace(/[-_.]+(.)/g, (_match, char: string) => char.toUpperCase());
  return `${camel}Plugin`;
}

/** A local alias per package, so two plugins whose ids camel-case alike cannot collide. */
function localAlias(pluginId: string, index: number): string {
  return `${descriptorExportName(pluginId)}_${index}`;
}

export function generateComposition(input: GenerationInput): GeneratedArtifact {
  const { inventory, graph } = input;

  // One import per *package*, in the resolved registration order, deduplicated: a multi-instance
  // plugin is one import and several entries.
  const packagesInOrder: { packageName: string; pluginId: string; packageVersion: string }[] = [];
  const seen = new Set<string>();
  for (const key of graph.order) {
    const instance = graph.instances.find((candidate) => candidate.key === key);
    if (!instance || seen.has(instance.packageName)) continue;
    seen.add(instance.packageName);
    packagesInOrder.push({
      packageName: instance.packageName,
      pluginId: instance.pluginId,
      packageVersion: instance.packageVersion,
    });
  }

  const aliasByPackage = new Map(
    packagesInOrder.map((entry, index) => [entry.packageName, localAlias(entry.pluginId, index)]),
  );

  const lines: string[] = [];
  lines.push('// GENERATED BY @appspine/plugin-cli — DO NOT EDIT.');
  lines.push('//');
  lines.push('// Run `appspine build` to regenerate, and `appspine build --check` to verify.');
  lines.push(`// sourceDigest: ${sourceDigest(input)}`);
  lines.push(`// resolutionDigest: ${graph.digest}`);
  lines.push('//');
  lines.push('// Every plugin below is a static import. Nothing here resolves a package name at');
  lines.push('// runtime: the bundler, TypeScript and a dependency scanner must all see the edge.');
  lines.push('');
  lines.push("import type { GeneratedComposition } from '@appspine/plugin-host-nest';");

  for (const entry of packagesInOrder) {
    const exported = descriptorExportName(entry.pluginId);
    const alias = aliasByPackage.get(entry.packageName) as string;
    lines.push(`import { ${exported} as ${alias} } from '${entry.packageName}/plugin';`);
  }

  lines.push('');
  lines.push('export const composition: GeneratedComposition = {');
  lines.push("  schemaVersion: 'appspine.composition/v1',");
  lines.push(`  resolutionDigest: ${JSON.stringify(graph.digest)},`);
  lines.push('  inventory: [');
  for (const entry of [...inventory.plugins].sort((a, b) =>
    `${a.plugin} ${a.instanceId}` < `${b.plugin} ${b.instanceId}` ? -1 : 1,
  )) {
    const fields = [
      `plugin: ${JSON.stringify(entry.plugin)}`,
      `instanceId: ${JSON.stringify(entry.instanceId)}`,
      `enabled: ${entry.enabled}`,
      `required: ${entry.required}`,
      ...(entry.configRef ? [`configRef: ${JSON.stringify(entry.configRef)}`] : []),
    ];
    lines.push(`    { ${fields.join(', ')} },`);
  }
  lines.push('  ],');
  lines.push('  plugins: [');
  for (const entry of packagesInOrder) {
    const alias = aliasByPackage.get(entry.packageName) as string;
    lines.push(
      `    { plugin: ${alias}, packageName: ${JSON.stringify(entry.packageName)}, packageVersion: ${JSON.stringify(entry.packageVersion)} },`,
    );
  }
  lines.push('  ],');
  lines.push(
    `  generatedBy: { tool: ${JSON.stringify(input.generatedBy.tool)}, version: ${JSON.stringify(input.generatedBy.version)} },`,
  );
  lines.push('};');
  lines.push('');
  lines.push('export default composition;');
  lines.push('');

  return { path: COMPOSITION_ARTIFACT, contents: lines.join('\n') };
}

/**
 * Refuses to emit a composition that cannot compile.
 *
 * A generator that writes a file referencing a subpath the package does not publish produces a
 * broken build with no explanation of where it came from. Better to say so here, naming the
 * package.
 */
export function compositionPreflight(input: GenerationInput): PluginDiagnostic[] {
  const diagnostics: PluginDiagnostic[] = [];
  for (const instance of input.graph.instances) {
    const loaded = [...input.manifests.byRef.values()].find(
      (candidate) => candidate.packageName === instance.packageName,
    );
    if (!loaded) continue;
    const backend = loaded.manifest.facets.backend;
    if (!backend) {
      diagnostics.push(
        diagnostic(
          'composition-without-backend',
          `"${instance.pluginId}" has no backend facet, so it contributes nothing to the Nest composition`,
          { pluginId: instance.pluginId, severity: 'info' },
        ),
      );
    }
  }
  return diagnostics;
}
