import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { runCli } from './cli';
import { COMMANDS } from './commands';
import { entry, manifest, type TestApp, testApp } from './commands/test-support';
import { COMPOSITION_ARTIFACT, descriptorExportName } from './composition';
import { ExitCode } from './exit-codes';
import { INVENTORY_FILENAME } from './inventory-file';
import { LOCKFILE_NAME, type PluginLockfile } from './lockfile';

const apps: TestApp[] = [];
afterEach(() => {
  while (apps.length > 0) rmSync(apps.pop()?.root as string, { recursive: true, force: true });
});

const AUDIT = manifest({
  id: 'audit-log',
  provides: ['appspine.audit-sink'],
  requires: ['appspine.prisma'],
});
const HEALTH = manifest({
  id: 'health-check',
  provides: ['appspine.health-indicator'],
  requires: ['appspine.prisma'],
});
const OIDC = manifest({
  id: 'oidc-auth',
  provides: ['appspine.interactive-auth-provider'],
  requires: ['appspine.audit-sink'],
  conflicts: ['local-auth'],
  configSchema: { configRef: 'oidc' },
});
const MULTI = manifest({
  id: 'master-data-client',
  cardinality: 'multiple',
  provides: ['appspine.master-data-client'],
  requires: [],
});

function make(options: Parameters<typeof testApp>[0]) {
  const created = testApp(options);
  apps.push(created);
  return created;
}

async function run(argv: string[], root: string) {
  const out: string[] = [];
  const code = await runCli([...argv, '--json', '--cwd', root], {
    commands: COMMANDS,
    version: '9.9.9',
    io: { stdout: (l) => out.push(l), stderr: () => {}, cwd: () => root },
  });
  const text = out.join('\n');
  return { code, envelope: JSON.parse(text.slice(text.lastIndexOf('{\n  "schemaVersion"'))) };
}

function compositionOf(root: string): string {
  return readFileSync(path.join(root, COMPOSITION_ARTIFACT), 'utf8');
}

describe('descriptorExportName', () => {
  it.each([
    ['health-check', 'healthCheckPlugin'],
    ['audit-log', 'auditLogPlugin'],
    ['identity-core', 'identityCorePlugin'],
    ['oidc-auth', 'oidcAuthPlugin'],
    ['master-data-client', 'masterDataClientPlugin'],
  ])('%s -> %s', (id, expected) => {
    expect(descriptorExportName(id)).toBe(expected);
  });
});

describe('generated composition', () => {
  it('imports every plugin statically', async () => {
    // 051 plan §6.4/§9: nothing may resolve a package name at runtime. A dynamic import is
    // invisible to the bundler, to TypeScript and to a dependency scanner — the three readers this
    // file exists for.
    const { root } = make({
      installed: [AUDIT, OIDC],
      inventory: [entry('audit-log'), entry('oidc-auth', { configRef: 'oidc' })],
    });

    await run(['build'], root);
    const source = compositionOf(root);

    expect(source).toContain("from '@appspine/audit-log/plugin';");
    expect(source).toContain("from '@appspine/oidc-auth/plugin';");
    expect(source).toMatch(/import \{ auditLogPlugin as \w+ \}/);
    expect(source).not.toMatch(/\bimport\s*\(/);
    expect(source).not.toMatch(/\brequire\s*\(/);
  });

  it('says it is generated and records both digests', async () => {
    const { root } = make({ installed: [AUDIT], inventory: [entry('audit-log')] });
    await run(['build'], root);
    const source = compositionOf(root);

    expect(source.startsWith('// GENERATED BY @appspine/plugin-cli — DO NOT EDIT.')).toBe(true);
    expect(source).toMatch(/\/\/ sourceDigest: sha256:/);
    expect(source).toMatch(/\/\/ resolutionDigest: sha256:/);
  });

  it('emits plugins in resolved registration order', async () => {
    const { root } = make({
      installed: [AUDIT, OIDC],
      inventory: [entry('oidc-auth', { configRef: 'oidc' }), entry('audit-log')],
    });

    await run(['build'], root);
    const source = compositionOf(root);

    // audit-log provides what oidc-auth requires, so it must be imported and registered first.
    expect(source.indexOf('audit-log/plugin')).toBeLessThan(source.indexOf('oidc-auth/plugin'));
  });

  it('imports a multi-instance plugin once and lists both instances', async () => {
    const { root } = make({
      installed: [MULTI],
      inventory: [
        entry('master-data-client', { instanceId: 'hr' }),
        entry('master-data-client', { instanceId: 'finance' }),
      ],
    });

    await run(['build'], root);
    const source = compositionOf(root);

    expect(source.match(/master-data-client\/plugin/g)).toHaveLength(1);
    expect(source).toContain('instanceId: "hr"');
    expect(source).toContain('instanceId: "finance"');
  });

  it('is byte-stable and independent of inventory order', async () => {
    const a = make({
      installed: [AUDIT, HEALTH],
      inventory: [entry('audit-log'), entry('health-check')],
    });
    const b = make({
      installed: [AUDIT, HEALTH],
      inventory: [entry('health-check'), entry('audit-log')],
    });

    await run(['build'], a.root);
    await run(['build'], b.root);

    expect(compositionOf(a.root)).toBe(compositionOf(b.root));
  });

  it('rebuilds from an inventory change alone', async () => {
    // 051 PL2-05's acceptance: enabling or disabling a plugin is an inventory edit plus a rebuild.
    // Nothing else in the App changes.
    const { root, addInstalled } = make({ installed: [AUDIT], inventory: [entry('audit-log')] });
    await run(['build'], root);
    expect(compositionOf(root)).not.toContain('health-check');

    addInstalled(HEALTH);
    writeFileSync(
      path.join(root, INVENTORY_FILENAME),
      `${JSON.stringify(
        {
          schemaVersion: 'appspine.plugins/v1',
          plugins: [entry('audit-log'), entry('health-check')],
        },
        null,
        2,
      )}\n`,
      'utf8',
    );

    await run(['build'], root);

    expect(compositionOf(root)).toContain("from '@appspine/health-check/plugin';");
  });

  it('drops a disabled plugin from the imports but keeps it in the inventory it embeds', async () => {
    const { root } = make({
      installed: [AUDIT, HEALTH],
      inventory: [entry('audit-log'), entry('health-check', { enabled: false })],
    });

    await run(['build'], root);
    const source = compositionOf(root);

    // Not imported: a disabled plugin must not end up in the bundle.
    expect(source).not.toContain("from '@appspine/health-check/plugin';");
    // Still in the inventory the host receives, so the catalog can report it as disabled.
    expect(source).toContain('"@appspine/health-check"');
    expect(source).toContain('enabled: false');
  });
});

describe('composition and the rest of the derived state', () => {
  it('is digested in the lockfile alongside the catalog', async () => {
    const { root } = make({ installed: [AUDIT], inventory: [entry('audit-log')] });
    await run(['build'], root);

    const lock = JSON.parse(readFileSync(path.join(root, LOCKFILE_NAME), 'utf8')) as PluginLockfile;
    expect(lock.artifacts.map((a) => a.path)).toEqual([
      '.appspine/generated/backend/composition.ts',
      '.appspine/generated/catalog.json',
    ]);
  });

  it('is covered by the drift check', async () => {
    const { root } = make({ installed: [AUDIT], inventory: [entry('audit-log')] });
    await run(['build'], root);

    const file = path.join(root, COMPOSITION_ARTIFACT);
    writeFileSync(file, `${readFileSync(file, 'utf8')}\n// hand-edited\n`, 'utf8');

    const { code, envelope } = await run(['build', '--check'], root);

    expect(code).toBe(ExitCode.DRIFT_DETECTED);
    expect(envelope.data.drift).toContainEqual({
      path: COMPOSITION_ARTIFACT,
      reason: 'stale',
    });
  });
});
